language: c
solution: DRWin.sln
os:
  #- linux
  #- osx
  - windows

#notifications:
 # email:
  #  on_failure: change # default: always

#addons:
  # Packages for Linux
 # apt:
  #  packages:
   #   - mingw-w64

env:
  - MAKE_BUILD=make
 # - MAKE_BUILD=debug

before_install:
  # Packages for OSX
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install mingw-w64; fi


script:
  - xbuild CI\ DRWin.sln
  #- if [ $MAKE_BUILD = make ]; then make; fi
  #- if [ $MAKE_BUILD = debug ]; then make debug; fi

#after_script:
 # - make clean
